FROM ubuntu:latest




RUN apt-get update && apt-get install -yqq \
    ufw \
    openssl \
    bridge-utils \
    net-tools \
    iptables \
    openvpn \
    easy-rsa 

WORKDIR /etc/openvpn
COPY ./data .
RUN chmod a+x -R . 




#RUN \
#echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf & \
#sysctl -p

COPY ./scripts/easyrsa /usr/share/easy-rsa/easyrsa
COPY ./scripts/bridge-start.sh .
COPY ./scripts/start.sh .
COPY ./scripts/bridge-stop.sh .

RUN ln -s /usr/share/easy-rsa/easyrsa /usr/local/bin

RUN chmod +x ./bridge-start.sh
RUN chmod +x ./start.sh


ENV DEBIAN_FRONTEND=noninteractive
ENV OPENVPN=/etc/openvpn
ENV EASYRSA=/usr/share/easy-rsa \
    EASYRSA_CRL_DAYS=3650 \
    EASYRSA_PKI=$OPENVPN/pki \
    EASYRSA_VARS_FILE=$OPENVPN/vars 



EXPOSE 1194/udp
CMD ./start.sh