FROM ubuntu:latest




RUN apt-get update && apt-get install -yqq \
    ufw \
    openssl \
    net-tools \
    iptables \
    openvpn \
    easy-rsa 

WORKDIR /etc/openvpn
COPY ./data .
RUN chmod a+x -R . 

COPY ./firewall/before.rules /etc/ufw/
COPY ./firewall/ufw /etc/default/

RUN \
echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf & \
sysctl -p

COPY ./scripts/easyrsa /usr/share/easy-rsa/easyrsa
RUN ln -s /usr/share/easy-rsa/easyrsa /usr/local/bin

ENV DEBIAN_FRONTEND=noninteractive
ENV OPENVPN=/etc/openvpn
ENV EASYRSA=/usr/share/easy-rsa \
    EASYRSA_CRL_DAYS=3650 \
    EASYRSA_PKI=$OPENVPN/pki \
    EASYRSA_VARS_FILE=$OPENVPN/vars 



EXPOSE 1194/udp
CMD ufw enable & ufw allow 1194/udp & ufw reload & /etc/init.d/openvpn start & tail -f /dev/null