FROM ubuntu:latest

RUN apt-get update && apt-get install -yqq \
    ufw \
    openssl \
    net-tools \
    iptables \
    openvpn 

WORKDIR /etc/openvpn
COPY ./data .
RUN chmod a+x -R . 

COPY ./firewall/before.rules /etc/ufw/
COPY ./firewall/ufw /etc/default/

ENV DEBIAN_FRONTEND=noninteractive
ENV OPENVPN=/etc/openvpn

EXPOSE 1194/udp
CMD ufw enable & ufw allow 1194/tcp & ufw reload & /etc/init.d/openvpn start & tail -f /dev/null
