FROM ubuntu:latest

RUN useradd -ms /bin/bash alice && echo 'alice:12345' | chpasswd && \
    useradd -ms /bin/bash bob   && echo 'bob:12345'   | chpasswd && \
    useradd -ms /bin/bash carl  && echo 'carl:12345'  | chpasswd && \
    echo 'root:12345' | chpasswd

ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -yqq \
    sudo \ 
    net-tools \
    iptables \
    openssh-server \
    apache2 \
    gpg \
    ettercap-text-only \
    nmap \
    tcpdump \
    iputils-ping \
    curl \
    libpcap-dev libusb-1.0-0-dev libnetfilter-queue-dev iproute2

COPY ./binaries/bettercap /usr/bin
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
    service ssh start

CMD ["/usr/sbin/sshd","-D"]
