FROM ubuntu:18.04

RUN apt-get update && apt-get install -yqq \
    ufw \
    openssl \
    net-tools \
    iptables \
    openvpn 

WORKDIR /etc/openvpn
COPY ./data .
RUN chmod a+x -R . 

COPY ./firewall/before.rules /etc/ufw/
COPY ./firewall/ufw /etc/default/

COPY ./scripts/entrypoint.sh ./

ENV DEBIAN_FRONTEND=noninteractive
ENV OPENVPN=/etc/openvpn

CMD ./entrypoint.sh
